### ISSUE TITLE
poor description of using that

### ISSUE THREAD

**Issue by cristo1985** [mvojtkovszky/DrawingView#2]
description or help = 0 .... is that a shit?

**Comment by mvojtkovszky** [comment]
Can you be a bit more specific?

**Comment by mvojtkovszky** [comment]
It extends a View. All public methods belong to it and are documented. 
If you think description requires more details, it's an open source project, feel free to do a pull request. Otherwise ask a more specific question and perhaps then I can help you then.

**Comment by cristo1985** [comment]
ok ok sorry for my arrogance .... lately i'm very nervous .... due to the late paychecks ... so okay ... i'd be interested to see if there is a way to load a drawable image .
